language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer install --no-progress --prefer-dist

script:
  # Nette/Tester
  - echo "OK"

jobs:
  include:
    - env: title="Lowest Dependencies 5.6"
      php: 5.6
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest
      script:
        - echo "OK"

    - env: title="Lowest Dependencies 7.1"
      php: 7.1
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest
      script:
        - echo "OK"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
